# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

domain: maanavsingh.me
url: https://maanavsingh.me


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Maanav Singh
email: maanavsingh1234@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Maanav Singh's Personal Website
github_username:  MaanavS16

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
locale: "en-US"
markdown: kramdown

search: true
lunr:
  search_within_pages: true


social:
  type:  Person
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://www.linkedin.com/in/maanav-singh/"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-GD4T9PFCGR"
    anonymize_ip: false # default

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache


# Site Author
author:
  name             : "Maanav Singh"
  #avatar          : "/assets/images/re_li_pfp.png"
  avatar           : "https://avatars.githubusercontent.com/u/50304418" 
  bio              : "CS and Math Student at UNC Chapel Hill"
  location         : "Morrisville, NC"
  email            : "msingh2@unc.edu"
  uri              : 
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "maanavs16"
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "maanav-singh"
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          :
  youtube          :

sass:
    load_paths: 
        - _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
include: ["_pages"]
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      classes: wide
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
